Ene: ene.models.TrackModel Class Reference
ene.models.TrackModel Class Reference
Public Member Functions
String getFilename ()
void setFilename (String filename)
String getArtist ()
void setArtist (String artist)
String getTitle ()
void setTitle (String title)
String getGenre ()
void setGenre (String genre)
TrackModel (String filename, String artist, String title, String genre)
String toString ()
Public Member Functions inherited from ene.models.AbstractModel
void addView (PartialView<?, ?> view)
Static Public Member Functions
static String detectArtist (String filename)
static String detectTitle (String filename)
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Protected Member Functions
static String cutFilenameFromPath (String path)
Protected Attributes
String filename
String artist
String title
String genre
Protected Attributes inherited from ene.models.AbstractModel
List< PartialView<?, ?> > views = new ArrayList<>()
Additional Inherited Members
Protected Member Functions inherited from ene.models.AbstractModel
void changed ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Track model.
Version
2.1.1
Definition at line 9 of file TrackModel.java.
Constructor & Destructor Documentation
TrackModel()
ene.models.TrackModel.TrackModel (String filename, String artist, String title, String genre)
Constructor.
Parameters
filename Filename.
artist Artist.
title Title.
genre Genre.
Since
0.10.0
Definition at line 106 of file TrackModel.java.
References ene.models.TrackModel.setArtist(), ene.models.TrackModel.setFilename(), ene.models.TrackModel.setGenre(), and ene.models.TrackModel.setTitle().
Member Function Documentation
cutFilenameFromPath()
static String ene.models.TrackModel.cutFilenameFromPath (String path) static protected
Cuts the filenme from a given path.
Parameters
path File path.
Returns
Returns the filename without it's path.
Since
1.0.0
Version
1.0.0
Definition at line 175 of file TrackModel.java.
References ene.models.TrackModel.filename.
Referenced by ene.models.TrackModel.detectArtist(), and ene.models.TrackModel.detectTitle().
detectArtist()
static String ene.models.TrackModel.detectArtist (String filename) static
Detects the artist by the filenme.
Parameters
filename The filename.
Returns
Returns the artist or a empty string.
Since
0.10.1
Version
2.0.0
Definition at line 133 of file TrackModel.java.
References ene.models.TrackModel.cutFilenameFromPath().
Referenced by ene.controllers.LibraryController.addFile(), and ene.controllers.PlaylistController.loadFromFile().
detectTitle()
static String ene.models.TrackModel.detectTitle (String filename) static
Detects the title by the filenme.
Parameters
filename The filename.
Returns
Returns the title or a empty string.
Since
0.10.1
Version
2.0.0
Definition at line 150 of file TrackModel.java.
References ene.models.TrackModel.cutFilenameFromPath(), and ene.models.TrackModel.filename.
Referenced by ene.controllers.LibraryController.addFile(), and ene.controllers.PlaylistController.loadFromFile().
getArtist()
String ene.models.TrackModel.getArtist ()
Get the artist.
Returns
Artist.
Definition at line 51 of file TrackModel.java.
References ene.models.TrackModel.artist.
Referenced by ene.models.LibraryModel.getByArtist(), ene.views.gui.partial.PlaylistView.loadContent(), ene.views.gui.partial.LibraryView.loadContent(), ene.views.gui.partial.LibraryView.render(), ene.controllers.PlaylistController.saveToFile(), ene.controllers.LibraryController.saveToFile(), ene.models.LibraryModel.search(), and ene.models.TrackModel.toString().
getFilename()
String ene.models.TrackModel.getFilename ()
Get the filename.
Returns
Filename.
Definition at line 34 of file TrackModel.java.
References ene.models.TrackModel.filename.
Referenced by ene.models.TrackListModel.add(), ene.models.LibraryModel.getByArtist(), ene.models.LibraryModel.getByGenre(), ene.models.LibraryModel.getByTitle(), ene.views.gui.partial.PlayerView.isCurrentTrackPartOfCurrentPlaylist(), ene.models.PlayerModel.load(), ene.views.gui.partial.PlaylistView.loadContent(), ene.views.gui.partial.LibraryView.loadContent(), ene.models.PlaylistModel.nextTrack(), ene.models.PlaylistModel.previousTrack(), ene.controllers.PlaylistController.saveToFile(), ene.controllers.LibraryController.saveToFile(), ene.models.LibraryModel.search(), and ene.models.TrackModel.toString().
getGenre()
String ene.models.TrackModel.getGenre ()
Get the genre.
Returns
Genre.
Definition at line 85 of file TrackModel.java.
References ene.models.TrackModel.genre.
Referenced by ene.models.LibraryModel.getByGenre(), ene.views.gui.partial.LibraryView.loadContent(), ene.views.gui.partial.LibraryView.render(), ene.controllers.LibraryController.saveToFile(), ene.models.LibraryModel.search(), and ene.models.TrackModel.toString().
getTitle()
String ene.models.TrackModel.getTitle ()
Get the title.
Returns
Title.
Definition at line 68 of file TrackModel.java.
References ene.models.TrackModel.title.
Referenced by ene.models.LibraryModel.getByTitle(), ene.views.gui.partial.PlaylistView.loadContent(), ene.views.gui.partial.LibraryView.loadContent(), ene.views.gui.partial.LibraryView.render(), ene.controllers.PlaylistController.saveToFile(), ene.controllers.LibraryController.saveToFile(), ene.models.LibraryModel.search(), and ene.models.TrackModel.toString().
setArtist()
void ene.models.TrackModel.setArtist (String artist)
Set the artist.
Parameters
artist Artist.
Definition at line 59 of file TrackModel.java.
References ene.models.TrackModel.artist, and ene.models.AbstractModel.changed().
Referenced by ene.models.TrackModel.TrackModel().
setFilename()
void ene.models.TrackModel.setFilename (String filename)
Set the filename.
Parameters
filename Filename.
Definition at line 42 of file TrackModel.java.
References ene.models.AbstractModel.changed(), and ene.models.TrackModel.filename.
Referenced by ene.models.TrackModel.TrackModel().
setGenre()
void ene.models.TrackModel.setGenre (String genre)
Set the genre
Parameters
genre Genre.
Definition at line 93 of file TrackModel.java.
References ene.models.AbstractModel.changed(), and ene.models.TrackModel.genre.
Referenced by ene.models.TrackModel.TrackModel().
setTitle()
void ene.models.TrackModel.setTitle (String title)
Set the title.
Parameters
title Title.
Definition at line 76 of file TrackModel.java.
References ene.models.AbstractModel.changed(), and ene.models.TrackModel.title.
Referenced by ene.models.TrackModel.TrackModel().
toString()
String ene.models.TrackModel.toString ()
Returns a string representation of the object.
Returns
String representation of the object.
Definition at line 117 of file TrackModel.java.
References ene.models.TrackModel.getArtist(), ene.models.TrackModel.getFilename(), ene.models.TrackModel.getGenre(), and ene.models.TrackModel.getTitle().
Member Data Documentation
artist
String ene.models.TrackModel.artist protected
Artist.
Definition at line 18 of file TrackModel.java.
Referenced by ene.models.TrackModel.getArtist(), and ene.models.TrackModel.setArtist().
filename
String ene.models.TrackModel.filename protected
Filename.
Definition at line 13 of file TrackModel.java.
Referenced by ene.models.TrackModel.cutFilenameFromPath(), ene.models.TrackModel.detectTitle(), ene.models.TrackModel.getFilename(), and ene.models.TrackModel.setFilename().
genre
String ene.models.TrackModel.genre protected
Genre.
Definition at line 28 of file TrackModel.java.
Referenced by ene.models.TrackModel.getGenre(), and ene.models.TrackModel.setGenre().
title
String ene.models.TrackModel.title protected
Title.
Definition at line 23 of file TrackModel.java.
Referenced by ene.models.TrackModel.getTitle(), and ene.models.TrackModel.setTitle().
The documentation for this class was generated from the following file:
src/ene/models/TrackModel.java