Ene: ene.views.gui.partial.AbstractTrackListView Class Reference
ene.views.gui.partial.AbstractTrackListView Class Reference abstract
Public Member Functions
void valueChanged (ListSelectionEvent event)
Public Member Functions inherited from ene.views.AbstractPartialView< CoreComponentType, ModelType >
void setModel (Model model)
ModelType getModel ()
Public Member Functions inherited from ene.views.AbstractView< CoreComponentType >
void setTitle (String title)
String getTitle ()
void setCoreComponent (CoreComponentType coreComponent)
CoreComponentType getCoreComponent ()
void setLayoutPosition (String layoutPosition)
String getLayoutPosition ()
Public Member Functions inherited from ene.interfaces.View< CoreComponentType >
void render ()
Public Member Functions inherited from ene.interfaces.Localization
default String getString (String stringName)
Public Member Functions inherited from ene.interfaces.PartialView< CoreComponentType, ModelType >
void update ()
Protected Member Functions
void setTable (JTable table)
JTable getTable ()
void setTableContent (DefaultTableModel tableContent)
DefaultTableModel getTableContent ()
void setPlayerController (Controller playerController)
PlayerController getPlayerController ()
void hideColumn (JTable table, int columnIndex)
String getSelectedFilename ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes
JTable table
DefaultTableModel tableContent
PlayerController playerController
Protected Attributes inherited from ene.views.AbstractPartialView< CoreComponentType, ModelType >
ModelType model
Protected Attributes inherited from ene.views.AbstractView< CoreComponentType >
String title = ""
CoreComponentType coreComponent
String layoutPosition
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Public Attributes inherited from ene.interfaces.Localization
static final String DEFAULT_LOCALE = "en_US"
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Track list view.
Since
0.14.0
Version
2.0.0
Definition at line 19 of file AbstractTrackListView.java.
Member Function Documentation
getPlayerController()
PlayerController ene.views.gui.partial.AbstractTrackListView.getPlayerController () protected
Returns the player controller instance.
Returns
Player controller instance.
Definition at line 89 of file AbstractTrackListView.java.
References ene.views.gui.partial.AbstractTrackListView.playerController.
Referenced by ene.views.gui.partial.AbstractTrackListView.valueChanged().
getSelectedFilename()
String ene.views.gui.partial.AbstractTrackListView.getSelectedFilename () protected
Returns the selected filename.
Returns
Selected filename or empty string, if nothing is selected.
Since
0.12.0
Definition at line 109 of file AbstractTrackListView.java.
References ene.views.gui.partial.AbstractTrackListView.getTable().
Referenced by ene.views.gui.partial.LibraryView.render(), and ene.views.gui.partial.AbstractTrackListView.valueChanged().
getTable()
JTable ene.views.gui.partial.AbstractTrackListView.getTable () protected
Returns the table instance.
Returns
Table instance.
Definition at line 57 of file AbstractTrackListView.java.
References ene.views.gui.partial.AbstractTrackListView.table.
Referenced by ene.views.gui.partial.AbstractTrackListView.getSelectedFilename().
getTableContent()
DefaultTableModel ene.views.gui.partial.AbstractTrackListView.getTableContent () protected
Returns the table content instance.
Returns
Table content instance.
Definition at line 73 of file AbstractTrackListView.java.
References ene.views.gui.partial.AbstractTrackListView.tableContent.
Referenced by ene.views.gui.partial.LibraryView.loadContent(), and ene.views.gui.partial.LibraryView.render().
hideColumn()
void ene.views.gui.partial.AbstractTrackListView.hideColumn (JTable table, int columnIndex) protected
Hide table column.
Parameters
table Table instance.
columnIndex Column index.
Definition at line 98 of file AbstractTrackListView.java.
Referenced by ene.views.gui.partial.LibraryView.render().
setPlayerController()
void ene.views.gui.partial.AbstractTrackListView.setPlayerController (Controller playerController) protected
Sets the player controller instance.
Parameters
playerController Player controller instance.
Definition at line 81 of file AbstractTrackListView.java.
Referenced by ene.views.gui.partial.LibraryView.LibraryView().
setTable()
void ene.views.gui.partial.AbstractTrackListView.setTable (JTable table) protected
Sets the table instance.
Parameters
table Table instance.
Definition at line 49 of file AbstractTrackListView.java.
References ene.views.gui.partial.AbstractTrackListView.table.
Referenced by ene.views.gui.partial.LibraryView.render().
setTableContent()
void ene.views.gui.partial.AbstractTrackListView.setTableContent (DefaultTableModel tableContent) protected
Sets the table content instance.
Parameters
tableContent Table content instance.
Definition at line 65 of file AbstractTrackListView.java.
References ene.views.gui.partial.AbstractTrackListView.tableContent.
valueChanged()
void ene.views.gui.partial.AbstractTrackListView.valueChanged (ListSelectionEvent event)
Definition at line 119 of file AbstractTrackListView.java.
References ene.AbstractObject.debugInfoAbout(), ene.views.AbstractPartialView< CoreComponentType, ModelType >.getModel(), ene.views.gui.partial.AbstractTrackListView.getPlayerController(), ene.views.gui.partial.AbstractTrackListView.getSelectedFilename(), and ene.controllers.PlayerController.load().
Member Data Documentation
playerController
PlayerController ene.views.gui.partial.AbstractTrackListView.playerController protected
Player controller instance.
Definition at line 43 of file AbstractTrackListView.java.
Referenced by ene.views.gui.partial.AbstractTrackListView.getPlayerController().
table
JTable ene.views.gui.partial.AbstractTrackListView.table protected
Table instance.
Definition at line 23 of file AbstractTrackListView.java.
Referenced by ene.views.gui.partial.AbstractTrackListView.getTable(), ene.views.gui.partial.LibraryView.render(), and ene.views.gui.partial.AbstractTrackListView.setTable().
tableContent
DefaultTableModel ene.views.gui.partial.AbstractTrackListView.tableContent protected
Initial value:
= new DefaultTableModel() {
        private static final long serialVersionUID = 1L;
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
Table content instance.
Definition at line 28 of file AbstractTrackListView.java.
Referenced by ene.views.gui.partial.AbstractTrackListView.getTableContent(), ene.views.gui.partial.LibraryView.loadContent(), ene.views.gui.partial.LibraryView.render(), and ene.views.gui.partial.AbstractTrackListView.setTableContent().
The documentation for this class was generated from the following file:
src/ene/views/gui/partial/AbstractTrackListView.java