Ene: ene.views.gui.partial.ContentView Class Reference
ene.views.gui.partial.ContentView Class Reference
Public Member Functions
ContentView (View<?> ... views)
void render ()
Public Member Functions inherited from ene.views.AbstractMasterView< CoreComponentType >
void addView (View<?> view)
void setAllViews (List< View<?>> views)
List< View<?> > getAllViews ()
Public Member Functions inherited from ene.views.AbstractView< CoreComponentType >
void setTitle (String title)
String getTitle ()
void setCoreComponent (CoreComponentType coreComponent)
CoreComponentType getCoreComponent ()
void setLayoutPosition (String layoutPosition)
String getLayoutPosition ()
Public Member Functions inherited from ene.interfaces.Localization
default String getString (String stringName)
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Public Attributes inherited from ene.interfaces.Localization
static final String DEFAULT_LOCALE = "en_US"
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes inherited from ene.views.AbstractMasterView< CoreComponentType >
List< View<?> > views = new ArrayList<>()
Protected Attributes inherited from ene.views.AbstractView< CoreComponentType >
String title = ""
CoreComponentType coreComponent
String layoutPosition
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Content view.
Version
4.1.0
Since
0.13.0
Definition at line 13 of file ContentView.java.
Constructor & Destructor Documentation
ContentView()
ene.views.gui.partial.ContentView.ContentView (View<?> ... views)
Constructor.
Parameters
views View instances.
Definition at line 18 of file ContentView.java.
References ene.views.AbstractMasterView< CoreComponentType >.addView().
Member Function Documentation
render()
void ene.views.gui.partial.ContentView.render ()
Renders the view.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 25 of file ContentView.java.
References ene.views.AbstractMasterView< CoreComponentType >.getAllViews(), and ene.views.AbstractView< CoreComponentType >.setCoreComponent().
The documentation for this class was generated from the following file:
src/ene/views/gui/partial/ContentView.java