Ene: ene.models.PlayerModel Class Reference
ene.models.PlayerModel Class Reference
Public Member Functions
Clip getClip ()
LineEvent getLastEvent ()
int getTrackLength ()
void setTrackPosition (int position)
int getTrackPosition ()
boolean load (TrackModel track)
boolean start ()
boolean pause ()
void update (LineEvent event)
Public Member Functions inherited from ene.models.AbstractModel
void addView (PartialView view)
Protected Member Functions
void setClip (Clip clip)
void setLastEvent (LineEvent event)
Protected Member Functions inherited from ene.models.AbstractModel
void changed ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Package Attributes
Clip clip
LineEvent lastEvent
int trackLength
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Protected Attributes inherited from ene.models.AbstractModel
List< PartialView > views = new ArrayList<>()
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Player model.
Version
1.0.0
Definition at line 18 of file PlayerModel.java.
Member Function Documentation
getClip()
Clip ene.models.PlayerModel.getClip ()
Returns the clip.
Returns
Clip instance.
Definition at line 46 of file PlayerModel.java.
References ene.models.PlayerModel.clip.
Referenced by ene.models.PlayerModel.getTrackLength(), ene.models.PlayerModel.getTrackPosition(), ene.models.PlayerModel.load(), ene.models.PlayerModel.pause(), ene.models.PlayerModel.setTrackPosition(), and ene.models.PlayerModel.start().
getLastEvent()
LineEvent ene.models.PlayerModel.getLastEvent ()
Returns the last event.
Returns
Line event instance.
Definition at line 62 of file PlayerModel.java.
References ene.models.PlayerModel.lastEvent.
getTrackLength()
int ene.models.PlayerModel.getTrackLength ()
Returns the track length.
Returns
Track length in seconds.
Definition at line 70 of file PlayerModel.java.
References ene.AbstractObject.delay(), and ene.models.PlayerModel.getClip().
Referenced by ene.views.gui.partial.PlayerView.update().
getTrackPosition()
int ene.models.PlayerModel.getTrackPosition ()
Returns the current track position.
Returns
Current track position in seconds.
Definition at line 87 of file PlayerModel.java.
References ene.AbstractObject.delay(), and ene.models.PlayerModel.getClip().
Referenced by ene.models.PlayerModel.setTrackPosition(), and ene.views.gui.partial.PlayerView.update().
load()
boolean ene.models.PlayerModel.load (TrackModel track)
Load track. Implementation inpired by: https://www.tutorials.de/threads/kontinuierlich-laufende-hintergrundmusik-in-java.359029
Parameters
track Track model instance.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 98 of file PlayerModel.java.
References ene.AbstractObject.debugInfoAbout(), ene.models.PlayerModel.getClip(), ene.models.TrackModel.getFilename(), and ene.models.PlayerModel.setClip().
pause()
boolean ene.models.PlayerModel.pause ()
Pause playing.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 140 of file PlayerModel.java.
References ene.AbstractObject.debugInfoAbout(), and ene.models.PlayerModel.getClip().
setClip()
void ene.models.PlayerModel.setClip (Clip clip) protected
Sets the clip.
Parameters
clip Clip instance.
Definition at line 38 of file PlayerModel.java.
References ene.models.PlayerModel.clip.
Referenced by ene.models.PlayerModel.load().
setLastEvent()
void ene.models.PlayerModel.setLastEvent (LineEvent event) protected
Sets the last event.
Parameters
event Line event instance.
Definition at line 54 of file PlayerModel.java.
Referenced by ene.models.PlayerModel.update().
setTrackPosition()
void ene.models.PlayerModel.setTrackPosition (int position)
Sets the current track position.
Parameters
position Track position in seconds.
Definition at line 79 of file PlayerModel.java.
References ene.models.PlayerModel.getClip(), and ene.models.PlayerModel.getTrackPosition().
start()
boolean ene.models.PlayerModel.start ()
Start playing.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 126 of file PlayerModel.java.
References ene.AbstractObject.debugInfoAbout(), and ene.models.PlayerModel.getClip().
update()
void ene.models.PlayerModel.update (LineEvent event)
Definition at line 151 of file PlayerModel.java.
References ene.models.AbstractModel.changed(), ene.AbstractObject.debugInfoAbout(), and ene.models.PlayerModel.setLastEvent().
Member Data Documentation
clip
Clip ene.models.PlayerModel.clip package
Clip instance.
Definition at line 22 of file PlayerModel.java.
Referenced by ene.models.PlayerModel.getClip(), and ene.models.PlayerModel.setClip().
lastEvent
LineEvent ene.models.PlayerModel.lastEvent package
Line event instance.
Definition at line 27 of file PlayerModel.java.
Referenced by ene.models.PlayerModel.getLastEvent().
trackLength
int ene.models.PlayerModel.trackLength package
Track length.
Definition at line 32 of file PlayerModel.java.
The documentation for this class was generated from the following file:
src/ene/models/PlayerModel.java