Ene: ene.models.PlaylistModel Class Reference
ene.models.PlaylistModel Class Reference
Public Member Functions
void setCurrentTrack (String filename)
TrackModel getCurrentTrack ()
void previousTrack ()
void nextTrack ()
Public Member Functions inherited from ene.models.TrackListModel
void add (TrackModel track)
boolean remove (String filename)
TrackModel get (String filename)
boolean has (String filename)
NavigableMap< String, TrackModel > getAll ()
Public Member Functions inherited from ene.models.AbstractModel
void addView (PartialView<?, ?> view)
Protected Attributes
TrackModel currentTrack = null
Protected Attributes inherited from ene.models.TrackListModel
NavigableMap< String, TrackModel > tracks = new TreeMap<>()
Protected Attributes inherited from ene.models.AbstractModel
List< PartialView<?, ?> > views = new ArrayList<>()
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Protected Member Functions inherited from ene.models.AbstractModel
void changed ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Playlist model.
Since
0.14.0
Version
2.0.0
Definition at line 10 of file PlaylistModel.java.
Member Function Documentation
getCurrentTrack()
TrackModel ene.models.PlaylistModel.getCurrentTrack ()
Returns the current track.
Returns
The current track model instance.
Definition at line 29 of file PlaylistModel.java.
References ene.models.PlaylistModel.currentTrack, and ene.models.TrackListModel.getAll().
Referenced by ene.models.PlayerModel.loadPlaylist(), ene.models.PlayerModel.next(), ene.models.PlaylistModel.nextTrack(), ene.models.PlayerModel.previous(), and ene.models.PlaylistModel.previousTrack().
nextTrack()
void ene.models.PlaylistModel.nextTrack ()
Jumps to the next track.
Returns
The next track model instance.
Definition at line 56 of file PlaylistModel.java.
References ene.models.AbstractModel.changed(), ene.models.TrackListModel.getAll(), ene.models.PlaylistModel.getCurrentTrack(), ene.models.TrackModel.getFilename(), and ene.models.PlaylistModel.setCurrentTrack().
Referenced by ene.models.PlayerModel.next().
previousTrack()
void ene.models.PlaylistModel.previousTrack ()
Jumps to the previous track.
Definition at line 40 of file PlaylistModel.java.
References ene.models.AbstractModel.changed(), ene.models.TrackListModel.getAll(), ene.models.PlaylistModel.getCurrentTrack(), ene.models.TrackModel.getFilename(), and ene.models.PlaylistModel.setCurrentTrack().
Referenced by ene.models.PlayerModel.previous().
setCurrentTrack()
void ene.models.PlaylistModel.setCurrentTrack (String filename)
Sets the current track.
Parameters
filename File path.
Definition at line 20 of file PlaylistModel.java.
References ene.models.AbstractModel.changed().
Referenced by ene.views.gui.partial.PlaylistView.mousePressed(), ene.models.PlaylistModel.nextTrack(), and ene.models.PlaylistModel.previousTrack().
Member Data Documentation
currentTrack
TrackModel ene.models.PlaylistModel.currentTrack = null protected
The current track model instance.
Definition at line 14 of file PlaylistModel.java.
Referenced by ene.models.PlaylistModel.getCurrentTrack().
The documentation for this class was generated from the following file:
src/ene/models/PlaylistModel.java