Ene: ene.controllers.LibraryController Class Reference
ene.controllers.LibraryController Class Reference
Public Member Functions
LibraryController (Model model)
LibraryController (Model model, String databaseFilename)
boolean loadFromFile (String filename)
boolean saveToFile (String filename)
boolean add (String filename)
boolean remove (String filename)
Public Member Functions inherited from ene.controllers.AbstractController< LibraryModel >
void setModel (Model model)
ModelType getModel ()
Protected Member Functions
void setDatabaseFilename (String filename)
String getDatabaseFilename ()
boolean addFile (File file, String ... genre)
boolean addDirectoryContent (File directory)
int scan (File path, String ... genre)
Protected Attributes
String databaseFilename
Protected Attributes inherited from ene.controllers.AbstractController< LibraryModel >
ModelType model
Static Protected Attributes
static final int DATABASE_TIMEOUT = 30
static final String DATABASE_TABLE = "tracks"
Detailed Description
Library controller.
Version
3.1.0
Definition at line 17 of file LibraryController.java.
Constructor & Destructor Documentation
LibraryController() [1/2]
ene.controllers.LibraryController.LibraryController (Model model)
Contructor.
Parameters
model Library model instance.
Version
1.0.0
Definition at line 56 of file LibraryController.java.
References ene.controllers.AbstractController< LibraryModel >.setModel().
LibraryController() [2/2]
ene.controllers.LibraryController.LibraryController (Model model, String databaseFilename)
Contructor.
Parameters
model Library model instance.
databaseFilename Database file path.
Since
0.16.0
Version
1.0.0
Definition at line 67 of file LibraryController.java.
References ene.controllers.LibraryController.loadFromFile(), ene.controllers.LibraryController.setDatabaseFilename(), and ene.controllers.AbstractController< LibraryModel >.setModel().
Member Function Documentation
add()
boolean ene.controllers.LibraryController.add (String filename)
Adds a file to the library.
Parameters
filename File path.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Since
0.12.0
Version
1.1.0
Definition at line 153 of file LibraryController.java.
References ene.controllers.LibraryController.addDirectoryContent(), ene.controllers.LibraryController.addFile(), ene.controllers.LibraryController.getDatabaseFilename(), and ene.controllers.LibraryController.saveToFile().
Referenced by ene.views.gui.partial.LibraryView.render().
addDirectoryContent()
boolean ene.controllers.LibraryController.addDirectoryContent (File directory) protected
Adds the files of a whole directory to the library.
Parameters
directory File instance of the directory.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 210 of file LibraryController.java.
References ene.controllers.LibraryController.scan().
Referenced by ene.controllers.LibraryController.add().
addFile()
boolean ene.controllers.LibraryController.addFile (File file, String ... genre) protected
Adds a file to the library.
Parameters
file File instance.
genre Given track genre (Optional, for internal usage only).
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 189 of file LibraryController.java.
References ene.models.TrackModel.detectArtist(), ene.models.TrackModel.detectTitle(), and ene.controllers.AbstractController< LibraryModel >.getModel().
Referenced by ene.controllers.LibraryController.add(), and ene.controllers.LibraryController.scan().
getDatabaseFilename()
String ene.controllers.LibraryController.getDatabaseFilename () protected
Returns the database file path.
Returns
Database file path.
Since
0.16.0
Definition at line 47 of file LibraryController.java.
References ene.controllers.LibraryController.databaseFilename.
Referenced by ene.controllers.LibraryController.add(), and ene.controllers.LibraryController.remove().
loadFromFile()
boolean ene.controllers.LibraryController.loadFromFile (String filename)
Loads the model from a file.
Parameters
filename File path.
Returns
Returns TRUE if successful. Otherwise FALSE.
Since
0.16.0
Version
1.0.0
Definition at line 80 of file LibraryController.java.
References ene.controllers.AbstractController< LibraryModel >.getModel(), and ene.interfaces.DatabaseConnection.query().
Referenced by ene.controllers.LibraryController.LibraryController().
remove()
boolean ene.controllers.LibraryController.remove (String filename)
Removes a file from the library.
Parameters
filename File path.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Since
0.10.0
Version
1.1.0
Definition at line 175 of file LibraryController.java.
References ene.controllers.LibraryController.getDatabaseFilename(), ene.controllers.AbstractController< LibraryModel >.getModel(), and ene.controllers.LibraryController.saveToFile().
saveToFile()
boolean ene.controllers.LibraryController.saveToFile (String filename)
Save the model to a file.
Parameters
filename File path.
Returns
Returns TRUE if successful. Otherwise FALSE.
Since
0.16.0
Version
1.0.0
Definition at line 123 of file LibraryController.java.
References ene.interfaces.DatabaseConnection.execute(), ene.models.TrackModel.getArtist(), ene.models.TrackModel.getFilename(), ene.models.TrackModel.getGenre(), and ene.models.TrackModel.getTitle().
Referenced by ene.controllers.LibraryController.add(), and ene.controllers.LibraryController.remove().
scan()
int ene.controllers.LibraryController.scan (File path, String ... genre) protected
Scans and adds files recursively.
Parameters
path File instance of the path.
genre Given track genre (Optional, for internal usage only).
Returns
Returns the amount of added files.
Definition at line 224 of file LibraryController.java.
References ene.controllers.LibraryController.addFile().
Referenced by ene.controllers.LibraryController.addDirectoryContent().
setDatabaseFilename()
void ene.controllers.LibraryController.setDatabaseFilename (String filename) protected
Sets the database file path.
Parameters
filename Database file path.
Since
0.16.0
Definition at line 38 of file LibraryController.java.
Referenced by ene.controllers.LibraryController.LibraryController().
Member Data Documentation
DATABASE_TABLE
final String ene.controllers.LibraryController.DATABASE_TABLE = "tracks" static protected
Database table name.
Definition at line 26 of file LibraryController.java.
DATABASE_TIMEOUT
final int ene.controllers.LibraryController.DATABASE_TIMEOUT = 30 static protected
Database connection timeout in seconds.
Definition at line 21 of file LibraryController.java.
databaseFilename
String ene.controllers.LibraryController.databaseFilename protected
Database file path.
Definition at line 31 of file LibraryController.java.
Referenced by ene.controllers.LibraryController.getDatabaseFilename().
The documentation for this class was generated from the following file:
src/ene/controllers/LibraryController.java