Ene: ene.views.gui.partial.LibraryView Class Reference
ene.views.gui.partial.LibraryView Class Reference
Public Member Functions
LibraryView (Model model, Controller libraryController, Controller playlistController, Controller playerController)
void update ()
void render ()
Public Member Functions inherited from ene.views.gui.partial.AbstractTrackListView
void mouseClicked (MouseEvent event)
void mousePressed (MouseEvent event)
void mouseReleased (MouseEvent event)
void mouseEntered (MouseEvent event)
void mouseExited (MouseEvent event)
void valueChanged (ListSelectionEvent event)
Public Member Functions inherited from ene.views.AbstractPartialView< CoreComponentType, ModelType >
void setModel (Model model)
ModelType getModel ()
Public Member Functions inherited from ene.views.AbstractView< CoreComponentType >
void setTitle (String title)
String getTitle ()
void setCoreComponent (CoreComponentType coreComponent)
CoreComponentType getCoreComponent ()
void setLayoutPosition (String layoutPosition)
String getLayoutPosition ()
Public Member Functions inherited from ene.interfaces.Localization
default String getString (String stringName)
Protected Member Functions
void setLibraryController (Controller libraryController)
LibraryController getLibraryController ()
void setPlaylistController (Controller playlistController)
PlaylistController getPlaylistController ()
void loadContent (Map< String, TrackModel > tracks)
Protected Member Functions inherited from ene.views.gui.partial.AbstractTrackListView
void setTable (JTable table)
JTable getTable ()
void setTableContent (DefaultTableModel tableContent)
DefaultTableModel getTableContent ()
void setTableRowSorter (TableRowSorter< DefaultTableModel > tableRowSorter)
TableRowSorter< DefaultTableModel > getTableRowSorter ()
void setPlayerController (Controller playerController)
PlayerController getPlayerController ()
void hideColumn (JTable table, int columnIndex)
void setColumnWidth (JTable table, int columnIndex, int width)
String getSelectedFilename ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes
LibraryController libraryController
PlaylistController playlistController
Protected Attributes inherited from ene.views.gui.partial.AbstractTrackListView
JTable table
TableRowSorter< DefaultTableModel > tableRowSorter
DefaultTableModel tableContent
PlayerController playerController
Protected Attributes inherited from ene.views.AbstractPartialView< CoreComponentType, ModelType >
ModelType model
Protected Attributes inherited from ene.views.AbstractView< CoreComponentType >
String title = ""
CoreComponentType coreComponent
String layoutPosition
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Public Attributes inherited from ene.interfaces.Localization
static final String DEFAULT_LOCALE = "en_US"
Static Protected Attributes inherited from ene.views.gui.partial.AbstractTrackListView
static final int TABLE_COLUMN_FILENAME = 0
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Library view.
Version
2.6.0
Since
0.13.0
Definition at line 34 of file LibraryView.java.
Constructor & Destructor Documentation
LibraryView()
ene.views.gui.partial.LibraryView.LibraryView (Model model, Controller libraryController, Controller playlistController, Controller playerController)
Constructor.
Parameters
model Library model instance.
libraryController Library controller instance.
playlistController Playlist controller instance.
playerController Player controller instance.
Version
2.0.0
Definition at line 85 of file LibraryView.java.
References ene.interfaces.Model.addView(), ene.interfaces.Localization.getString(), ene.views.AbstractView< CoreComponentType >.setLayoutPosition(), ene.views.gui.partial.LibraryView.setLibraryController(), ene.views.AbstractPartialView< CoreComponentType, ModelType >.setModel(), ene.views.gui.partial.AbstractTrackListView.setPlayerController(), ene.views.gui.partial.LibraryView.setPlaylistController(), and ene.views.AbstractView< CoreComponentType >.setTitle().
Member Function Documentation
getLibraryController()
LibraryController ene.views.gui.partial.LibraryView.getLibraryController () protected
Returns the library controller instance.
Returns
Library controller instance.
Definition at line 57 of file LibraryView.java.
References ene.views.gui.partial.LibraryView.libraryController.
Referenced by ene.views.gui.partial.LibraryView.render().
getPlaylistController()
PlaylistController ene.views.gui.partial.LibraryView.getPlaylistController () protected
Returns the playlist controller instance.
Returns
Playlist controller instance.
Definition at line 73 of file LibraryView.java.
References ene.views.gui.partial.LibraryView.playlistController.
Referenced by ene.views.gui.partial.LibraryView.render().
loadContent()
void ene.views.gui.partial.LibraryView.loadContent (Map< String, TrackModel > tracks) protected
Loads the table content from the model.
Parameters
tracks Map of Tracks.
Definition at line 99 of file LibraryView.java.
References ene.models.TrackModel.getArtist(), ene.models.TrackModel.getFilename(), ene.models.TrackModel.getGenre(), ene.views.gui.partial.AbstractTrackListView.getTableContent(), ene.models.TrackModel.getTitle(), and ene.views.gui.partial.AbstractTrackListView.tableContent.
Referenced by ene.views.gui.partial.LibraryView.render(), and ene.views.gui.partial.LibraryView.update().
render()
void ene.views.gui.partial.LibraryView.render ()
Renders the view.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 114 of file LibraryView.java.
References ene.controllers.PlaylistController.add(), ene.controllers.LibraryController.add(), ene.controllers.LibraryController.edit(), ene.models.TrackModel.getArtist(), ene.views.AbstractView< CoreComponentType >.getCoreComponent(), ene.models.TrackModel.getGenre(), ene.views.gui.partial.LibraryView.getLibraryController(), ene.views.AbstractPartialView< CoreComponentType, ModelType >.getModel(), ene.views.gui.partial.LibraryView.getPlaylistController(), ene.views.gui.partial.AbstractTrackListView.getSelectedFilename(), ene.interfaces.Localization.getString(), ene.views.gui.partial.AbstractTrackListView.getTableContent(), ene.models.TrackModel.getTitle(), ene.views.gui.partial.AbstractTrackListView.hideColumn(), ene.views.gui.partial.LibraryView.loadContent(), ene.views.AbstractView< CoreComponentType >.setCoreComponent(), ene.views.gui.partial.AbstractTrackListView.setTable(), ene.views.gui.partial.AbstractTrackListView.setTableRowSorter(), ene.views.gui.partial.AbstractTrackListView.table, ene.views.gui.partial.AbstractTrackListView.TABLE_COLUMN_FILENAME, ene.views.gui.partial.AbstractTrackListView.tableContent, ene.views.gui.partial.AbstractTrackListView.tableRowSorter, ene.views.AbstractView< CoreComponentType >.title, and ene.views.gui.partial.LibraryView.update().
setLibraryController()
void ene.views.gui.partial.LibraryView.setLibraryController (Controller libraryController) protected
Sets the library controller instance.
Parameters
libraryController Library controller instance.
Definition at line 49 of file LibraryView.java.
Referenced by ene.views.gui.partial.LibraryView.LibraryView().
setPlaylistController()
void ene.views.gui.partial.LibraryView.setPlaylistController (Controller playlistController) protected
Sets the playlist controller instance.
Parameters
playlistController Playlist controller instance.
Definition at line 65 of file LibraryView.java.
Referenced by ene.views.gui.partial.LibraryView.LibraryView().
update()
void ene.views.gui.partial.LibraryView.update ()
Request update.
Implements ene.interfaces.PartialView< CoreComponentType, ModelType >.
Definition at line 109 of file LibraryView.java.
References ene.views.AbstractPartialView< CoreComponentType, ModelType >.getModel(), and ene.views.gui.partial.LibraryView.loadContent().
Referenced by ene.views.gui.partial.LibraryView.render().
Member Data Documentation
libraryController
LibraryController ene.views.gui.partial.LibraryView.libraryController protected
Library controller instance.
Definition at line 38 of file LibraryView.java.
Referenced by ene.views.gui.partial.LibraryView.getLibraryController().
playlistController
PlaylistController ene.views.gui.partial.LibraryView.playlistController protected
Playlist controller instance.
Definition at line 43 of file LibraryView.java.
Referenced by ene.views.gui.partial.LibraryView.getPlaylistController().
The documentation for this class was generated from the following file:
src/ene/views/gui/partial/LibraryView.java