Ene: ene.databases.SQLDatabase Class Reference
ene.databases.SQLDatabase Class Reference
Public Member Functions
SQLDatabase (String url, int statementTimeout) throws Exception
SQLDatabase (String url, int statementTimeout, Properties properties) throws Exception
int execute (String statement) throws Exception
List< Map< String, String > > query (String statement) throws Exception
Protected Member Functions
void setConnection (Connection connection)
Connection getConnection ()
void setStatement (Statement statement)
Statement getStatement ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes
Connection connection = null
Statement statement = null
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
JDBC SQL database.
Version
1.1.0
Definition at line 20 of file SQLDatabase.java.
Constructor & Destructor Documentation
SQLDatabase() [1/2]
ene.databases.SQLDatabase.SQLDatabase (String url, int statementTimeout) throws Exception
Constructor.
Parameters
url A database url of the form jdbc:subprotocol:subname.
statementTimeout Statement timeout in seconds.
Version
1.0.0
Definition at line 69 of file SQLDatabase.java.
References ene.databases.SQLDatabase.getConnection(), ene.databases.SQLDatabase.getStatement(), ene.databases.SQLDatabase.setConnection(), and ene.databases.SQLDatabase.setStatement().
SQLDatabase() [2/2]
ene.databases.SQLDatabase.SQLDatabase (String url, int statementTimeout, Properties properties) throws Exception
Constructor.
Parameters
url A database url of the form jdbc:subprotocol:subname.
statementTimeout Statement timeout in seconds.
properties Properties instance.
Since
0.16.0
Version
1.0.0
Definition at line 83 of file SQLDatabase.java.
References ene.databases.SQLDatabase.getConnection(), ene.databases.SQLDatabase.getStatement(), ene.databases.SQLDatabase.setConnection(), and ene.databases.SQLDatabase.setStatement().
Member Function Documentation
execute()
int ene.databases.SQLDatabase.execute (String statement) throws Exception
Executes statement.
Parameters
statement Statement.
Returns
Number of affected rows.
Implements ene.interfaces.DatabaseConnection.
Definition at line 90 of file SQLDatabase.java.
References ene.databases.SQLDatabase.getStatement().
getConnection()
Connection ene.databases.SQLDatabase.getConnection () protected
Returns the connection instance.
Returns
Connection instance.
Definition at line 43 of file SQLDatabase.java.
References ene.databases.SQLDatabase.connection.
Referenced by ene.databases.SQLDatabase.SQLDatabase().
getStatement()
Statement ene.databases.SQLDatabase.getStatement () protected
Returns the statement instance.
Returns
Statement instance.
Definition at line 59 of file SQLDatabase.java.
References ene.databases.SQLDatabase.statement.
Referenced by ene.databases.SQLDatabase.execute(), ene.databases.SQLDatabase.query(), and ene.databases.SQLDatabase.SQLDatabase().
query()
List<Map<String,String> > ene.databases.SQLDatabase.query (String statement) throws Exception
Query statement.
Parameters
statement Statement.
Returns
Returns a list of maps of rows.
Implements ene.interfaces.DatabaseConnection.
Definition at line 95 of file SQLDatabase.java.
References ene.databases.SQLDatabase.getStatement().
setConnection()
void ene.databases.SQLDatabase.setConnection (Connection connection) protected
Sets the connection instance.
Parameters
connection Connection instance.
Definition at line 35 of file SQLDatabase.java.
References ene.databases.SQLDatabase.connection.
Referenced by ene.databases.SQLDatabase.SQLDatabase().
setStatement()
void ene.databases.SQLDatabase.setStatement (Statement statement) protected
Sets the statement instance.
Parameters
statement Statement instance.
Definition at line 51 of file SQLDatabase.java.
References ene.databases.SQLDatabase.statement.
Referenced by ene.databases.SQLDatabase.SQLDatabase().
Member Data Documentation
connection
Connection ene.databases.SQLDatabase.connection = null protected
Connection instance.
Definition at line 24 of file SQLDatabase.java.
Referenced by ene.databases.SQLDatabase.getConnection(), and ene.databases.SQLDatabase.setConnection().
statement
Statement ene.databases.SQLDatabase.statement = null protected
Statement instance.
Definition at line 29 of file SQLDatabase.java.
Referenced by ene.databases.SQLDatabase.getStatement(), and ene.databases.SQLDatabase.setStatement().
The documentation for this class was generated from the following file:
src/ene/databases/SQLDatabase.java