Ene: ene.views.gui.WindowView Class Reference
ene.views.gui.WindowView Class Reference
Public Member Functions
void setTitle (String title)
String getTitle ()
WindowView (View ... views)
void render ()
Public Member Functions inherited from ene.views.AbstractMasterView< CoreComponentType >
void addView (View view)
void setAllViews (List< View > views)
List< View > getAllViews ()
Public Member Functions inherited from ene.views.AbstractView< CoreComponentType >
void setTitle (String title)
String getTitle ()
void setCoreComponent (CoreComponentType coreComponent)
CoreComponentType getCoreComponent ()
void setLayoutPosition (String layoutPosition)
String getLayoutPosition ()
Public Member Functions inherited from ene.interfaces.Localization
default String getString (String stringName)
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Public Attributes inherited from ene.interfaces.Localization
static final String DEFAULT_LOCALE = "en_US"
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes inherited from ene.views.AbstractMasterView< CoreComponentType >
List< View > views = new ArrayList<>()
Protected Attributes inherited from ene.views.AbstractView< CoreComponentType >
String title = ""
CoreComponentType coreComponent
String layoutPosition
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Window view.
Version
1.3.0
Definition at line 20 of file WindowView.java.
Constructor & Destructor Documentation
WindowView()
ene.views.gui.WindowView.WindowView (View ... views)
Constructor.
Parameters
views View instances.
Definition at line 35 of file WindowView.java.
References ene.views.AbstractMasterView< CoreComponentType >.addView().
Member Function Documentation
getTitle()
String ene.views.gui.WindowView.getTitle ()
Returns the title.
Returns
Title.
Since
0.13.0
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 27 of file WindowView.java.
References ene.views.AbstractView< CoreComponentType >.getCoreComponent().
render()
void ene.views.gui.WindowView.render ()
Renders the view.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 42 of file WindowView.java.
References ene.views.AbstractMasterView< CoreComponentType >.getAllViews(), ene.interfaces.Localization.getString(), ene.views.AbstractView< CoreComponentType >.setCoreComponent(), and ene.views.gui.WindowView.setTitle().
setTitle()
void ene.views.gui.WindowView.setTitle (String title)
Sets the title.
Parameters
title Title.
Since
0.13.0
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 22 of file WindowView.java.
References ene.views.AbstractView< CoreComponentType >.getCoreComponent().
Referenced by ene.views.gui.WindowView.render().
The documentation for this class was generated from the following file:
src/ene/views/gui/WindowView.java