Ene: ene.views.gui.partial.PlayerView Class Reference
ene.views.gui.partial.PlayerView Class Reference
Public Member Functions
PlayerView (Model model, Controller<?> playerController)
void update ()
void render ()
Public Member Functions inherited from ene.views.AbstractPartialView< CoreComponentType, ModelType >
void setModel (Model model)
ModelType getModel ()
Public Member Functions inherited from ene.views.AbstractView< CoreComponentType >
void setTitle (String title)
String getTitle ()
void setCoreComponent (CoreComponentType coreComponent)
CoreComponentType getCoreComponent ()
void setLayoutPosition (String layoutPosition)
String getLayoutPosition ()
Public Member Functions inherited from ene.interfaces.Localization
default String getString (String stringName)
Protected Member Functions
void setPlayerController (Controller<?> playerController)
PlayerController getPlayerController ()
void enablePlayerControls ()
void disablePlayerControls ()
void updateProgress ()
void resetProgress ()
String formatTimeToString (int timeInSeconds)
boolean isCurrentTrackPartOfCurrentPlaylist (PlayerModel player)
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes
PlayerController playerController
JButton previousButton
JButton playButton
JButton nextButton
JSlider progressSlider
JLabel progressLabel
Protected Attributes inherited from ene.views.AbstractPartialView< CoreComponentType, ModelType >
ModelType model
Protected Attributes inherited from ene.views.AbstractView< CoreComponentType >
String title = ""
CoreComponentType coreComponent
String layoutPosition
Package Attributes
Timer progressTimer
SimpleDateFormat trackTimeFormat
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Public Attributes inherited from ene.interfaces.Localization
static final String DEFAULT_LOCALE = "en_US"
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Player view.
Version
2.2.1
Definition at line 26 of file PlayerView.java.
Constructor & Destructor Documentation
PlayerView()
ene.views.gui.partial.PlayerView.PlayerView (Model model, Controller<?> playerController)
Constructor.
Parameters
model Player model instance.
playerController Player controller instance.
Version
1.1.0
Definition at line 89 of file PlayerView.java.
References ene.interfaces.Model.addView(), ene.views.AbstractView< CoreComponentType >.setLayoutPosition(), ene.views.AbstractPartialView< CoreComponentType, ModelType >.setModel(), and ene.views.gui.partial.PlayerView.setPlayerController().
Member Function Documentation
disablePlayerControls()
void ene.views.gui.partial.PlayerView.disablePlayerControls () protected
Disables player controls.
Definition at line 112 of file PlayerView.java.
Referenced by ene.views.gui.partial.PlayerView.render(), and ene.views.gui.partial.PlayerView.update().
enablePlayerControls()
void ene.views.gui.partial.PlayerView.enablePlayerControls () protected
Enables player controls.
Definition at line 99 of file PlayerView.java.
References ene.views.AbstractPartialView< CoreComponentType, ModelType >.getModel(), and ene.views.gui.partial.PlayerView.isCurrentTrackPartOfCurrentPlaylist().
Referenced by ene.views.gui.partial.PlayerView.update().
formatTimeToString()
String ene.views.gui.partial.PlayerView.formatTimeToString (int timeInSeconds) protected
Returns a string representation of the time.
Parameters
timeInSeconds Time in seconds.
Returns
String representation of the time.
Definition at line 148 of file PlayerView.java.
Referenced by ene.views.gui.partial.PlayerView.updateProgress().
getPlayerController()
PlayerController ene.views.gui.partial.PlayerView.getPlayerController () protected
Returns the player controller instance.
Returns
Player controller instance.
Definition at line 79 of file PlayerView.java.
References ene.views.gui.partial.PlayerView.playerController.
Referenced by ene.views.gui.partial.PlayerView.render(), ene.views.gui.partial.PlayerView.resetProgress(), and ene.views.gui.partial.PlayerView.update().
isCurrentTrackPartOfCurrentPlaylist()
boolean ene.views.gui.partial.PlayerView.isCurrentTrackPartOfCurrentPlaylist (PlayerModel player) protected
Checks, if the current track a part of the current playlist is.
Returns
Returns TRUE, if it is a part of. Otherwise FALSE.
Since
1.0.0
Version
1.0.0
Definition at line 190 of file PlayerView.java.
References ene.models.PlayerModel.getCurrentTrack(), ene.models.TrackModel.getFilename(), ene.models.PlayerModel.getPlaylist(), and ene.models.TrackListModel.has().
Referenced by ene.views.gui.partial.PlayerView.enablePlayerControls(), and ene.views.gui.partial.PlayerView.update().
render()
void ene.views.gui.partial.PlayerView.render ()
Renders the view.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 203 of file PlayerView.java.
References ene.controllers.PlayerController.changeTrackPosition(), ene.AbstractObject.debugInfoAbout(), ene.views.gui.partial.PlayerView.disablePlayerControls(), ene.views.gui.partial.PlayerView.getPlayerController(), ene.interfaces.Localization.getString(), ene.controllers.PlayerController.next(), ene.controllers.PlayerController.previous(), ene.views.AbstractView< CoreComponentType >.setCoreComponent(), ene.controllers.PlayerController.togglePlayback(), and ene.views.gui.partial.PlayerView.updateProgress().
resetProgress()
void ene.views.gui.partial.PlayerView.resetProgress () protected
Resets the track progress.
Definition at line 138 of file PlayerView.java.
References ene.controllers.PlayerController.changeTrackPosition(), ene.views.gui.partial.PlayerView.getPlayerController(), and ene.views.gui.partial.PlayerView.updateProgress().
Referenced by ene.views.gui.partial.PlayerView.update().
setPlayerController()
void ene.views.gui.partial.PlayerView.setPlayerController (Controller<?> playerController) protected
Sets the player controller instance.
Parameters
playerController Player controller instance.
Definition at line 71 of file PlayerView.java.
Referenced by ene.views.gui.partial.PlayerView.PlayerView().
update()
void ene.views.gui.partial.PlayerView.update ()
Request update.
Implements ene.interfaces.PartialView< CoreComponentType, ModelType >.
Definition at line 153 of file PlayerView.java.
References ene.views.gui.partial.PlayerView.disablePlayerControls(), ene.views.gui.partial.PlayerView.enablePlayerControls(), ene.views.AbstractPartialView< CoreComponentType, ModelType >.getModel(), ene.views.gui.partial.PlayerView.getPlayerController(), ene.interfaces.Localization.getString(), ene.models.PlayerModel.getTrackLength(), ene.models.PlayerModel.getTrackPosition(), ene.views.gui.partial.PlayerView.isCurrentTrackPartOfCurrentPlaylist(), ene.controllers.PlayerController.next(), ene.views.gui.partial.PlayerView.resetProgress(), and ene.controllers.PlayerController.togglePlayback().
updateProgress()
void ene.views.gui.partial.PlayerView.updateProgress () protected
Updates the progress slider and label.
Definition at line 123 of file PlayerView.java.
References ene.views.gui.partial.PlayerView.formatTimeToString(), and ene.views.AbstractPartialView< CoreComponentType, ModelType >.getModel().
Referenced by ene.views.gui.partial.PlayerView.render(), and ene.views.gui.partial.PlayerView.resetProgress().
Member Data Documentation
nextButton
JButton ene.views.gui.partial.PlayerView.nextButton protected
Next button.
Definition at line 45 of file PlayerView.java.
playButton
JButton ene.views.gui.partial.PlayerView.playButton protected
Play/Pause button.
Definition at line 40 of file PlayerView.java.
playerController
PlayerController ene.views.gui.partial.PlayerView.playerController protected
Player controller instance.
Definition at line 30 of file PlayerView.java.
Referenced by ene.views.gui.partial.PlayerView.getPlayerController().
previousButton
JButton ene.views.gui.partial.PlayerView.previousButton protected
Previous button.
Definition at line 35 of file PlayerView.java.
progressLabel
JLabel ene.views.gui.partial.PlayerView.progressLabel protected
Progress label.
Definition at line 55 of file PlayerView.java.
progressSlider
JSlider ene.views.gui.partial.PlayerView.progressSlider protected
Progress slider.
Definition at line 50 of file PlayerView.java.
progressTimer
Timer ene.views.gui.partial.PlayerView.progressTimer package
Progress refresh timer.
Definition at line 60 of file PlayerView.java.
trackTimeFormat
SimpleDateFormat ene.views.gui.partial.PlayerView.trackTimeFormat package
Track time format instance.
Definition at line 65 of file PlayerView.java.
The documentation for this class was generated from the following file:
src/ene/views/gui/partial/PlayerView.java