Ene: ene.Application Class Reference
ene.Application Class Reference
Static Public Member Functions
static void main (String args[])
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Protected Member Functions
static void processArguments (String arguments[])
static void run ()
Static Protected Attributes
static final String LIBRARY_DATABASE_FILE = "library.db"
static final String PLAYLIST_FILE = "playlist.m3u"
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Additional Inherited Members
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Detailed Description
Bootstrap class.
Since
0.8.0
Version
1.3.0
Definition at line 24 of file Application.java.
Member Function Documentation
main()
static void ene.Application.main (String args[]) static
Entry point.
Parameters
args Arguments.
Version
1.0.0
Definition at line 41 of file Application.java.
References ene.Application.processArguments(), and ene.Application.run().
processArguments()
static void ene.Application.processArguments (String arguments[]) static protected
Processes arguments.
Parameters
arguments Arguments.
Version
1.0.0
Definition at line 51 of file Application.java.
References ene.AbstractObject.consoleOutput(), and ene.AbstractObject.enableDebugMode().
Referenced by ene.Application.main().
run()
static void ene.Application.run () static protected
Runs application.
Version
1.2.0
Definition at line 72 of file Application.java.
References ene.interfaces.View< CoreComponentType >.render().
Referenced by ene.Application.main().
Member Data Documentation
LIBRARY_DATABASE_FILE
final String ene.Application.LIBRARY_DATABASE_FILE = "library.db" static protected
Library database file path.
Definition at line 28 of file Application.java.
PLAYLIST_FILE
final String ene.Application.PLAYLIST_FILE = "playlist.m3u" static protected
Playlist file path.
Definition at line 33 of file Application.java.
The documentation for this class was generated from the following file:
src/ene/Application.java