Ene: ene.views.AbstractView< CoreComponentType > Class Template Reference
ene.views.AbstractView< CoreComponentType > Class Template Reference abstract
Public Member Functions
void setTitle (String title)
String getTitle ()
void setCoreComponent (CoreComponentType coreComponent)
CoreComponentType getCoreComponent ()
void setLayoutPosition (String layoutPosition)
String getLayoutPosition ()
Public Member Functions inherited from ene.interfaces.View< CoreComponentType >
void render ()
Public Member Functions inherited from ene.interfaces.Localization
default String getString (String stringName)
Protected Attributes
String title = ""
CoreComponentType coreComponent
String layoutPosition
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Public Attributes inherited from ene.interfaces.Localization
static final String DEFAULT_LOCALE = "en_US"
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Abstract view.
Version
1.1.0
Definition at line 11 of file AbstractView.java.
Member Function Documentation
getCoreComponent()
CoreComponentType ene.views.AbstractView< CoreComponentType >.getCoreComponent ()
Returns the core component instance.
Returns
Core component instance.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 43 of file AbstractView.java.
References ene.views.AbstractView< CoreComponentType >.coreComponent.
Referenced by ene.views.gui.WindowView.getTitle(), ene.views.gui.partial.LibraryView.render(), and ene.views.gui.WindowView.setTitle().
getLayoutPosition()
String ene.views.AbstractView< CoreComponentType >.getLayoutPosition ()
Returns the layout position.
Returns
Layout position.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 53 of file AbstractView.java.
References ene.views.AbstractView< CoreComponentType >.layoutPosition.
getTitle()
String ene.views.AbstractView< CoreComponentType >.getTitle ()
Returns the title.
Returns
Title.
Since
0.13.0
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 33 of file AbstractView.java.
References ene.views.AbstractView< CoreComponentType >.title.
setCoreComponent()
void ene.views.AbstractView< CoreComponentType >.setCoreComponent (CoreComponentType coreComponent)
Sets the core component instance.
Parameters
coreComponent Core component instance.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 38 of file AbstractView.java.
References ene.views.AbstractView< CoreComponentType >.coreComponent.
Referenced by ene.views.gui.partial.ContentView.render(), ene.views.gui.WindowView.render(), ene.views.gui.partial.PlaylistView.render(), ene.views.gui.partial.LibraryView.render(), and ene.views.gui.partial.PlayerView.render().
setLayoutPosition()
void ene.views.AbstractView< CoreComponentType >.setLayoutPosition (String layoutPosition)
Sets the layout position.
Parameters
layoutPosition Layout position.
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 48 of file AbstractView.java.
References ene.views.AbstractView< CoreComponentType >.layoutPosition.
Referenced by ene.views.gui.partial.LibraryView.LibraryView(), ene.views.gui.partial.PlayerView.PlayerView(), and ene.views.gui.partial.PlaylistView.PlaylistView().
setTitle()
void ene.views.AbstractView< CoreComponentType >.setTitle (String title)
Sets the title.
Parameters
title Title.
Since
0.13.0
Implements ene.interfaces.View< CoreComponentType >.
Definition at line 28 of file AbstractView.java.
References ene.views.AbstractView< CoreComponentType >.title.
Referenced by ene.views.gui.partial.LibraryView.LibraryView(), and ene.views.gui.partial.PlaylistView.PlaylistView().
Member Data Documentation
coreComponent
CoreComponentType ene.views.AbstractView< CoreComponentType >.coreComponent protected
Core component instance.
Definition at line 20 of file AbstractView.java.
Referenced by ene.views.AbstractView< CoreComponentType >.getCoreComponent(), and ene.views.AbstractView< CoreComponentType >.setCoreComponent().
layoutPosition
String ene.views.AbstractView< CoreComponentType >.layoutPosition protected
Layout position.
Definition at line 25 of file AbstractView.java.
Referenced by ene.views.AbstractView< CoreComponentType >.getLayoutPosition(), and ene.views.AbstractView< CoreComponentType >.setLayoutPosition().
title
String ene.views.AbstractView< CoreComponentType >.title = "" protected
Title.
Definition at line 15 of file AbstractView.java.
Referenced by ene.views.AbstractView< CoreComponentType >.getTitle(), ene.views.gui.partial.LibraryView.render(), and ene.views.AbstractView< CoreComponentType >.setTitle().
The documentation for this class was generated from the following file:
src/ene/views/AbstractView.java