Ene: ene.views.AbstractMasterView< CoreComponentType > Class Template Reference
ene.views.AbstractMasterView< CoreComponentType > Class Template Reference abstract
Public Member Functions
void addView (View<?> view)
void setAllViews (List< View<?>> views)
List< View<?> > getAllViews ()
Public Member Functions inherited from ene.views.AbstractView< CoreComponentType >
void setTitle (String title)
String getTitle ()
void setCoreComponent (CoreComponentType coreComponent)
CoreComponentType getCoreComponent ()
void setLayoutPosition (String layoutPosition)
String getLayoutPosition ()
Public Member Functions inherited from ene.interfaces.View< CoreComponentType >
void render ()
Public Member Functions inherited from ene.interfaces.Localization
default String getString (String stringName)
Protected Attributes
List< View<?> > views = new ArrayList<>()
Protected Attributes inherited from ene.views.AbstractView< CoreComponentType >
String title = ""
CoreComponentType coreComponent
String layoutPosition
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Public Attributes inherited from ene.interfaces.Localization
static final String DEFAULT_LOCALE = "en_US"
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Abstract master view.
Since
0.3.0
Version
1.0.0
Definition at line 14 of file AbstractMasterView.java.
Member Function Documentation
addView()
void ene.views.AbstractMasterView< CoreComponentType >.addView (View<?> view)
Adds view instance.
Parameters
view View instance.
Implements ene.interfaces.MasterView< CoreComponentType >.
Definition at line 21 of file AbstractMasterView.java.
Referenced by ene.views.gui.partial.ContentView.ContentView(), and ene.views.gui.WindowView.WindowView().
getAllViews()
List<View<?> > ene.views.AbstractMasterView< CoreComponentType >.getAllViews ()
Returns all contained view instances.
Returns
List of view instaces.
Implements ene.interfaces.MasterView< CoreComponentType >.
Definition at line 31 of file AbstractMasterView.java.
Referenced by ene.views.gui.partial.ContentView.render(), and ene.views.gui.WindowView.render().
setAllViews()
void ene.views.AbstractMasterView< CoreComponentType >.setAllViews (List< View<?>> views)
Sets all contained view instances.
Parameters
views List of view instaces.
Implements ene.interfaces.MasterView< CoreComponentType >.
Definition at line 26 of file AbstractMasterView.java.
Member Data Documentation
views
List<View<?> > ene.views.AbstractMasterView< CoreComponentType >.views = new ArrayList<>() protected
Contained view instances.
Definition at line 18 of file AbstractMasterView.java.
Referenced by ene.views.AbstractMasterView< JFrame >.getAllViews(), and ene.views.AbstractMasterView< JFrame >.setAllViews().
The documentation for this class was generated from the following file:
src/ene/views/AbstractMasterView.java