Ene: ene.models.LibraryModel Class Reference
ene.models.LibraryModel Class Reference
Public Member Functions
Map< String, TrackModel > getByArtist (String artist)
Map< String, TrackModel > getByTitle (String title)
Map< String, TrackModel > getByGenre (String genre)
Map< String, TrackModel > search (String title, String artist, String genre)
Public Member Functions inherited from ene.models.TrackListModel
void add (TrackModel track)
boolean remove (String filename)
TrackModel get (String filename)
boolean has (String filename)
NavigableMap< String, TrackModel > getAll ()
Public Member Functions inherited from ene.models.AbstractModel
void addView (PartialView<?, ?> view)
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Protected Member Functions inherited from ene.models.AbstractModel
void changed ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes inherited from ene.models.TrackListModel
NavigableMap< String, TrackModel > tracks = new TreeMap<>()
Protected Attributes inherited from ene.models.AbstractModel
List< PartialView<?, ?> > views = new ArrayList<>()
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Library model.
Version
4.1.0
Definition at line 12 of file LibraryModel.java.
Member Function Documentation
getByArtist()
Map<String, TrackModel> ene.models.LibraryModel.getByArtist (String artist)
Returns all tracks by an particular artist.
Parameters
artist Artist.
Returns
Tracks.
Since
0.10.0
Definition at line 19 of file LibraryModel.java.
References ene.models.TrackModel.getArtist(), ene.models.TrackModel.getFilename(), and ene.models.TrackListModel.tracks.
getByGenre()
Map<String, TrackModel> ene.models.LibraryModel.getByGenre (String genre)
Returns all tracks from a particular genre.
Parameters
genre Genre.
Returns
Tracks.
Since
0.10.0
Definition at line 53 of file LibraryModel.java.
References ene.models.TrackModel.getFilename(), ene.models.TrackModel.getGenre(), and ene.models.TrackListModel.tracks.
getByTitle()
Map<String, TrackModel> ene.models.LibraryModel.getByTitle (String title)
Returns all tracks with a particular title.
Parameters
title Title.
Returns
Tracks.
Since
0.10.0
Definition at line 36 of file LibraryModel.java.
References ene.models.TrackModel.getFilename(), ene.models.TrackModel.getTitle(), and ene.models.TrackListModel.tracks.
search()
Map<String, TrackModel> ene.models.LibraryModel.search (String title, String artist, String genre)
Returns all matching tracks.
Parameters
title Title.
artist Artist.
genre Genre.
Returns
Map of tracks and it's absolute file path.
Since
0.15.0
Version
1.0.0
Definition at line 73 of file LibraryModel.java.
References ene.models.TrackModel.getArtist(), ene.models.TrackModel.getFilename(), ene.models.TrackModel.getGenre(), ene.models.TrackModel.getTitle(), and ene.models.TrackListModel.tracks.
The documentation for this class was generated from the following file:
src/ene/models/LibraryModel.java