Ene: ene.models.TrackListModel Class Reference
ene.models.TrackListModel Class Reference
Public Member Functions
void add (TrackModel track)
boolean remove (String filename)
TrackModel get (String filename)
Map< String, TrackModel > getAll ()
Public Member Functions inherited from ene.models.AbstractModel
void addView (PartialView view)
Protected Attributes
Map< String, TrackModel > tracks = new HashMap<>()
Protected Attributes inherited from ene.models.AbstractModel
List< PartialView > views = new ArrayList<>()
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Protected Member Functions inherited from ene.models.AbstractModel
void changed ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Track list model.
Since
0.11.0
Version
1.0.0
Definition at line 12 of file TrackListModel.java.
Member Function Documentation
add()
void ene.models.TrackListModel.add (TrackModel track)
Adds a track.
Parameters
track Track model instance.
Definition at line 22 of file TrackListModel.java.
References ene.models.AbstractModel.changed(), and ene.models.TrackModel.getFilename().
get()
TrackModel ene.models.TrackListModel.get (String filename)
Returns track.
Parameters
filename File path.
Returns
Track.
Definition at line 46 of file TrackListModel.java.
getAll()
Map<String, TrackModel> ene.models.TrackListModel.getAll ()
Returns all tracks.
Returns
Tracks.
Definition at line 54 of file TrackListModel.java.
References ene.models.TrackListModel.tracks.
remove()
boolean ene.models.TrackListModel.remove (String filename)
Removes a track.
Parameters
filename File path.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 32 of file TrackListModel.java.
References ene.models.AbstractModel.changed().
Member Data Documentation
tracks
Map<String, TrackModel> ene.models.TrackListModel.tracks = new HashMap<>() protected
All tracks.
Definition at line 16 of file TrackListModel.java.
Referenced by ene.models.TrackListModel.getAll(), ene.models.LibraryModel.getByArtist(), ene.models.LibraryModel.getByGenre(), ene.models.LibraryModel.getByTitle(), and ene.models.LibraryModel.search().
The documentation for this class was generated from the following file:
src/ene/models/TrackListModel.java