Ene: ene.controllers.PlayerController Class Reference
ene.controllers.PlayerController Class Reference
Public Member Functions
PlayerController (Model model)
void changeTrackPosition (int newPosition)
boolean load (TrackModel track)
void togglePlayback ()
Public Member Functions inherited from ene.controllers.AbstractController< PlayerModel >
void setModel (Model model)
ModelType getModel ()
Additional Inherited Members
Protected Attributes inherited from ene.controllers.AbstractController< PlayerModel >
ModelType model
Detailed Description
Player controller.
Version
1.0.0
Definition at line 13 of file PlayerController.java.
Constructor & Destructor Documentation
PlayerController()
ene.controllers.PlayerController.PlayerController (Model model)
Constructor.
Parameters
model Player model instance.
Definition at line 18 of file PlayerController.java.
References ene.controllers.AbstractController< PlayerModel >.setModel().
Member Function Documentation
changeTrackPosition()
void ene.controllers.PlayerController.changeTrackPosition (int newPosition)
Changes the current track position.
Parameters
newPosition New track position in seconds.
Definition at line 26 of file PlayerController.java.
References ene.controllers.AbstractController< PlayerModel >.getModel().
Referenced by ene.views.gui.partial.PlayerView.render(), and ene.views.gui.partial.PlayerView.resetProgress().
load()
boolean ene.controllers.PlayerController.load (TrackModel track)
Load track.
Parameters
track Track instance.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 35 of file PlayerController.java.
References ene.controllers.AbstractController< PlayerModel >.getModel().
Referenced by ene.views.gui.partial.AbstractTrackListView.valueChanged().
togglePlayback()
void ene.controllers.PlayerController.togglePlayback ()
Toggle playback.
Definition at line 42 of file PlayerController.java.
References ene.controllers.AbstractController< PlayerModel >.getModel().
Referenced by ene.views.gui.partial.PlayerView.render().
The documentation for this class was generated from the following file:
src/ene/controllers/PlayerController.java