Ene: ene.models.AbstractModel Class Reference
ene.models.AbstractModel Class Reference abstract
Public Member Functions
void addView (PartialView view)
Protected Member Functions
void changed ()
Protected Member Functions inherited from ene.AbstractObject
void delay (long milliseconds)
Protected Attributes
List< PartialView > views = new ArrayList<>()
Additional Inherited Members
Static Public Member Functions inherited from ene.AbstractObject
static void enableDebugMode ()
static void disableDebugMode ()
static boolean isDebugModeEnabled ()
static void debugInfoAbout (Object object)
static void consoleOutput (String text)
Static Protected Attributes inherited from ene.AbstractObject
static boolean debugModeEnabled = false
Detailed Description
Abstract model.
Version
2.0.0
Definition at line 13 of file AbstractModel.java.
Member Function Documentation
addView()
void ene.models.AbstractModel.addView (PartialView view)
Add related view.
Parameters
view View.
Implements ene.interfaces.Model.
Definition at line 20 of file AbstractModel.java.
changed()
void ene.models.AbstractModel.changed () protected
Update event.
Definition at line 27 of file AbstractModel.java.
References ene.interfaces.PartialView< CoreComponentType, ModelType >.update().
Referenced by ene.models.TrackListModel.add(), ene.models.TrackListModel.remove(), ene.models.TrackModel.setArtist(), ene.models.TrackModel.setFilename(), ene.models.TrackModel.setGenre(), ene.models.TrackModel.setTitle(), and ene.models.PlayerModel.update().
Member Data Documentation
views
List<PartialView> ene.models.AbstractModel.views = new ArrayList<>() protected
Related views.
Definition at line 17 of file AbstractModel.java.
The documentation for this class was generated from the following file:
src/ene/models/AbstractModel.java