Ene: ene.controllers.PlaylistController Class Reference
ene.controllers.PlaylistController Class Reference
Public Member Functions
PlaylistController (Model model)
PlaylistController (Model model, String playlistFilename)
boolean loadFromFile (String filename)
boolean saveToFile (String filename)
boolean add (TrackModel track)
boolean remove (String filename)
Public Member Functions inherited from ene.controllers.AbstractController< PlaylistModel >
void setModel (Model model)
ModelType getModel ()
Protected Member Functions
void setPlaylistFilename (String filename)
String getPlaylistFilename ()
Protected Attributes
String playlistFilename
Protected Attributes inherited from ene.controllers.AbstractController< PlaylistModel >
ModelType model
Detailed Description
Playlist controller.
Since
1.0.0
Version
1.0.0
Definition at line 21 of file PlaylistController.java.
Constructor & Destructor Documentation
PlaylistController() [1/2]
ene.controllers.PlaylistController.PlaylistController (Model model)
Contructor.
Parameters
model Playlist model instance.
Version
1.0.0
Definition at line 48 of file PlaylistController.java.
References ene.controllers.AbstractController< PlaylistModel >.setModel().
PlaylistController() [2/2]
ene.controllers.PlaylistController.PlaylistController (Model model, String playlistFilename)
Contructor.
Parameters
model Playlist model instance.
playlistFilename Playlist file path.
Version
1.0.0
Definition at line 58 of file PlaylistController.java.
References ene.controllers.PlaylistController.loadFromFile(), ene.controllers.AbstractController< PlaylistModel >.setModel(), and ene.controllers.PlaylistController.setPlaylistFilename().
Member Function Documentation
add()
boolean ene.controllers.PlaylistController.add (TrackModel track)
Adds a track to the playlist.
Parameters
track Track model instance.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 123 of file PlaylistController.java.
References ene.controllers.AbstractController< PlaylistModel >.getModel(), ene.controllers.PlaylistController.getPlaylistFilename(), and ene.controllers.PlaylistController.saveToFile().
Referenced by ene.controllers.PlaylistController.loadFromFile(), and ene.views.gui.partial.LibraryView.render().
getPlaylistFilename()
String ene.controllers.PlaylistController.getPlaylistFilename () protected
Returns the playlist file path.
Returns
Playlist file path.
Definition at line 39 of file PlaylistController.java.
References ene.controllers.PlaylistController.playlistFilename.
Referenced by ene.controllers.PlaylistController.add(), and ene.controllers.PlaylistController.remove().
loadFromFile()
boolean ene.controllers.PlaylistController.loadFromFile (String filename)
Loads data from a file.
Parameters
filename File path.
Returns
Returns TRUE if successful. Otherwise FALSE.
Implements ene.interfaces.Import.
Definition at line 65 of file PlaylistController.java.
References ene.controllers.PlaylistController.add(), ene.models.TrackModel.detectArtist(), and ene.models.TrackModel.detectTitle().
Referenced by ene.controllers.PlaylistController.PlaylistController().
remove()
boolean ene.controllers.PlaylistController.remove (String filename)
Removes a track from the playlist.
Parameters
filename File path.
Returns
Returns TRUE, if successful. Otherwise FALSE.
Definition at line 133 of file PlaylistController.java.
References ene.controllers.AbstractController< PlaylistModel >.getModel(), ene.controllers.PlaylistController.getPlaylistFilename(), and ene.controllers.PlaylistController.saveToFile().
saveToFile()
boolean ene.controllers.PlaylistController.saveToFile (String filename)
Saves data to a file.
Parameters
filename File path.
Returns
Returns TRUE if successful. Otherwise FALSE.
Implements ene.interfaces.Export.
Definition at line 100 of file PlaylistController.java.
References ene.models.TrackModel.getArtist(), ene.models.TrackModel.getFilename(), and ene.models.TrackModel.getTitle().
Referenced by ene.controllers.PlaylistController.add(), and ene.controllers.PlaylistController.remove().
setPlaylistFilename()
void ene.controllers.PlaylistController.setPlaylistFilename (String filename) protected
Sets the playlist file path.
Parameters
filename Playlist file path.
Definition at line 31 of file PlaylistController.java.
Referenced by ene.controllers.PlaylistController.PlaylistController().
Member Data Documentation
playlistFilename
String ene.controllers.PlaylistController.playlistFilename protected
Playlist file path.
Definition at line 25 of file PlaylistController.java.
Referenced by ene.controllers.PlaylistController.getPlaylistFilename().
The documentation for this class was generated from the following file:
src/ene/controllers/PlaylistController.java