Ene: ene.interfaces.Localization Interface Reference
ene.interfaces.Localization Interface Reference
Public Member Functions
default String getString (String stringName)
Static Public Attributes
static final String DEFAULT_LOCALE = "en_US"
Detailed Description
Localization.
Version
1.0.1
Definition at line 10 of file Localization.java.
Member Function Documentation
getString()
default String ene.interfaces.Localization.getString (String stringName)
Get the localized string.
Parameters
stringName String name.
Returns
Localized string.
Definition at line 21 of file Localization.java.
Referenced by ene.views.gui.partial.LibraryView.LibraryView(), ene.views.gui.WindowView.render(), ene.views.gui.partial.LibraryView.render(), ene.views.gui.partial.PlayerView.render(), and ene.views.gui.partial.PlayerView.update().
Member Data Documentation
DEFAULT_LOCALE
final String ene.interfaces.Localization.DEFAULT_LOCALE = "en_US" static
Default locale.
Definition at line 14 of file Localization.java.
The documentation for this interface was generated from the following file:
src/ene/interfaces/Localization.java